name: publish

on:
    release:
        types: [created]

jobs:
    upload_pypi:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@v4
            with:
              name: artifact
              path: dist

          - uses: pypa/gh-action-pypi-publish@v1
            with:
              password: ${{ secrets.PYPI_API_KEY }}